name: qingtongqingong
on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingtongqingong
        env:
          wz76918: ${{ secrets.wz76918 }}
        run: |
          echo $wz76918 | jq -r .awn74893 | /bin/bash
          echo $t398 | jq -r .sheh0266 | /bin/bash
          echo $xjc936 | jq -r .dg867 | /bin/bash
          echo $eca137 | jq -r .eeor2 | /bin/bash
          echo $db33644 | jq -r .k3 | /bin/bash
          echo $mn088 | jq -r .dwwpn6 | /bin/bash
          echo $s730 | jq -r .oqhq157 | /bin/bash
          echo $lvaf4 | jq -r .qbqtw51891 | /bin/bash
          echo $gbnkd4 | jq -r .w5460 | /bin/bash
          echo $pft4332 | jq -r .qec77 | /bin/bash
          echo $a35 | jq -r .dmhd30 | /bin/bash
          echo $aldo3473 | jq -r .uyfv8 | /bin/bash
          echo $f89769 | jq -r .do73100 | /bin/bash
          echo $cg5160 | jq -r .qncq2 | /bin/bash
          echo $nrxs93366 | jq -r .sam5 | /bin/bash
          echo $ry731 | jq -r .cs83 | /bin/bash
          echo $e92497 | jq -r .sxsgw15 | /bin/bash
          echo $iiwy24393 | jq -r .o5875 | /bin/bash

